import { Inter } from "next/font/google";
import "./globals.css";
import { NextUIProvider } from "@nextui-org/react";
import AuthWrapper from "./auth_wrapper";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" className="dark">
      <body className={`${inter.className}`}>
        <AuthWrapper>
          {" "}
          <NextUIProvider>{children}</NextUIProvider>
        </AuthWrapper>
      </body>
    </html>
  );
}
